### PR TITLE
ID plugin

### LINKED ISSUE #2: Implement ID plugin
## New feature

Either an element or a code block should be able to get an HTML ID.

## Example usage

```` markdown
``` html #my-id
<p>Example</p>
```
````

``` markdown
# Headline <?: #my-id ?>
```

## Help

In case some hints are needed, [here is an example](https://gist.github.com/hagenburger/71925f9b15a0318a20f2371708cf28d9) which could be checked against.

### PR DESCRIPTION
**Pull request by artnerdnet**
Introduce ID plugin
This closes #2

### CODE REVIEW

**Comment by artnerdnet** [comment]
I'm getting this message when I try to run lint, any ideas what could it be? Gracias :)

$ npm run lint

> pimd@0.1.0 lint C:\Users\Violeta\dev\living\pimd
> eslint .

ESLint configuration in C:\Users\Violeta\dev\living\pimd\plugins\classes\.eslintrc is invalid:
        - Unexpected top-level property "0".

Error: ESLint configuration in C:\Users\Violeta\dev\living\pimd\plugins\classes\.eslintrc is invalid:
        - Unexpected top-level property "0".

    at validateConfigSchema (C:\Users\Violeta\dev\living\pimd\node_modules\eslint\lib\config\config-validator.js:221:15)
    at Object.validate (C:\Users\Violeta\dev\living\pimd\node_modules\eslint\lib\config\config-validator.js:238:5)
    at loadFromDisk (C:\Users\Violeta\dev\living\pimd\node_modules\eslint\lib\config\config-file.js:516:19)
    at Object.load (C:\Users\Violeta\dev\living\pimd\node_modules\eslint\lib\config\config-file.js:559:20)
    at Config.getLocalConfigHierarchy (C:\Users\Violeta\dev\living\pimd\node_modules\eslint\lib\config.js:227:44)
    at Config.getConfigHierarchy (C:\Users\Violeta\dev\living\pimd\node_modules\eslint\lib\config.js:179:43)
    at Config.getConfigVector (C:\Users\Violeta\dev\living\pimd\node_modules\eslint\lib\config.js:286:21)
    at Config.getConfig (C:\Users\Violeta\dev\living\pimd\node_modules\eslint\lib\config.js:329:29)
    at processText (C:\Users\Violeta\dev\living\pimd\node_modules\eslint\lib\cli-engine.js:163:33)
    at processFile (C:\Users\Violeta\dev\living\pimd\node_modules\eslint\lib\cli-engine.js:224:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pimd@0.1.0 lint: `eslint .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pimd@0.1.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Violeta\AppData\Roaming\npm-cache\_logs\2018-07-30T18_56_06_126Z-debug.log

**Comment by hagenburger** [comment]
Thanks for your updates! I’ll have a look later. There seems to be a misconfiguration in Hound CI, it raises too many errors. I’ll check this.

**Comment by hagenburger** [comment]
@artnerdnet @dianavile: I’m closing this and ask you to open the pull request again. I’m going to send you the details via Slack.

**Comment by benevbright** [comment]
@artnerdnet 
I requested PR that fixes lint error. #11

**Pull request closed without merging**
