### PR TITLE
Syntax highlighter + Highlight

### PR DESCRIPTION
**Pull request by hagenburger**
This is basically working but very open for better naming suggestions. Especially “highlighter extras” is not self-explanatory.

I put both features into one pull request to provide a better understanding how the “highlighter extras” will be used.

### CODE REVIEW

**Comment by benevbright** [comment]
HTMLInjection ?

**Comment by hagenburger** [comment]
@benevbright see description, I made that for understanding the use case only. It’s work in progress and not ready to be merged. I’d love to get some feedback, especially on the naming.

**Comment by hagenburger** [comment]
@benevbright not bad. I’ll think about it. I like the idea.

**Comment by hagenburger** [comment]
I’m closing this WIP pull request.

**Pull request closed without merging**
